### PR TITLE
Updates "msw" to 0.26.0 (latest)

### PR DESCRIPTION
**Pull request by kettanaito**
MSW needs to be updated and its worker scripts as well to have the smoke tests passing and all the examples using the latest version.

### CODE REVIEW

**Comment by kettanaito** [comment]
Even though the version is locked at `msw: latest`, it doesn't install the next minor version. Looks like the `yarn.lock` locks MSW.

**Comment by kettanaito** [comment]
Encountered this exception when running one of the tests:

```
  LoginForm
    ✓ should allow a user to log in (118ms)

  console.error ../../node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: window.computedStyle(elt, pseudoElt)
        at module.exports (/Users/kettanaito/Projects/mswjs/examples/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at Window.getComputedStyle (/Users/kettanaito/Projects/mswjs/examples/node_modules/jsdom/lib/jsdom/browser/Window.js:657:7)
        at computeMiscTextAlternative (/Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/dom-accessibility-api/sources/accessible-name.ts:306:62)
        at computeTextAlternative (/Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/dom-accessibility-api/sources/accessible-name.ts:521:11)
        at computeAccessibleName (/Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/dom-accessibility-api/sources/accessible-name.ts:552:3)
        at /Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/queries/role.js:72:82
        at Array.filter (<anonymous>)
        at queryAllByRole (/Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/queries/role.js:66:6)
        at /Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:68:17
        at /Users/kettanaito/Projects/mswjs/examples/node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:54:17 undefined
```

Seems to be connected to https://github.com/testing-library/dom-testing-library/issues/774 and requires an update to `@testing-library/dom`.

**Comment by kettanaito** [comment]
@timdeschryver thank you for fixing the build. I've rebased upon the latest master, took your version of `yarn.lock` during the merge conflicts resolution. Still think I might have screwed things a little. Let's wait for the build...

**Comment by timdeschryver** [comment]
Seems like it's green 🥳

**Pull request closed without merging**
