### PR TITLE
migrate to msw-storybook-addon

### PR DESCRIPTION
**Pull request by itaditya**
## Changes

Replace the custom msw integration with msw-storybook-addon.

## Questions

1. In my local, storyshot tests are not running even on master branch. Can the maintainers verify if this issue is only on my end?

The error is "Unexpected error while loading ./GitHubUser.stories.js: SyntaxError: Unexpected token '.'"

image

2. The loading story is showing error in UI on master branch. Can this be verified as well?

image

3. There is an error in console saying service worker is outdated. I have updated it but not committed, should I add that?

image

4. What should I update in the readme?

msw-storybook-addon has good Getting Started docs, should I copy it? Or should I put link to them in "Start the mocking" section.

## Example checklist

- [x] **I've followed the [Contribution guidelines](./CONTRIBUTING.md)**.
- [x] I've verified that all added tests pass by running `npm test`.
- [x] I've included only the necessary minimum setup to showcase the example.
- [x] I've added a `README.md` file to the root directory of my example.

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @itaditya. Thank you for preparing this!

> In my local, storyshot tests are not running even on master branch. Can the maintainers verify if this issue is only on my end?

The Storybook tests are disabled on `master`. There's an issue with the storyshoots addon that renders it unable to handle `*.css` files imported in a story's component. I trust I've raised this in Storybook/addon repo, but haven't got any info back.

We may as well consider migrating the tests there to Cypress, but let's not face this at the moment. 

> The loading story is showing error in UI on master branch. Can this be verified as well?

I'll look into this and let you know. 

> What should I update in the readme?

You can reference the addon's docs with the getting started instructions, no need to repeat them.

**Comment by itaditya** [comment]
We can also use Chromatic to get visual snapshot testing for free.

https://www.chromatic.com/pricing

**Comment by itaditya** [comment]
Also what to do about Q3

> There is an error in console saying service worker is outdated. I have updated it but not committed, should I add that?

**Comment by kettanaito** [comment]
> I am using Chromatic in msw addon docs also

Can you please show how are you writing/running in-Storybook tests with Chromatic? 

I've found [some integration tests](https://github.com/mswjs/msw-storybook-addon/blob/f76f510530191c0efdd69f369acdee2e8d677a94/packages/docs/src/demos/axios/App.test.js), but to be more confident we should a) run/build Storybook with demos, b) run in-browser tests that assert UI based on responses. Integration tests are great, but here we are looking for in-browser verification, closer to where our demos are functioning.

**Comment by itaditya** [comment]
> The loading story is showing error in UI on master branch. Can this be verified as well?

> I'll look into this and let you know.

Hey @kettanaito did you get time to look into this?

> Can you please show how are you writing/running in-Storybook tests with Chromatic?

Chromatic doesn't need any testing code. We only need to run a CLI command on CI. Their service opens Storybook in a browser through their server and takes a screenshot of the Canvas. The downside is that it doesn't let us simulate user interactions before taking screenshot.

**Comment by itaditya** [comment]
@kettanaito I've done the following-

1. Update Readme to include the link to addon docs. Please suggest if the wording needs to be changed.
2. Update the generated SW file.
3. Tested storyshots is working after commenting out the CSS file import.

**Comment by kettanaito** [comment]
Hi, @itaditya. Once again, thanks for the work on this update 👏 I've just refreshed the entire collection of examples, and we don't currently have a Storybook example to apply this to. I will work on it in the future.

**Pull request closed without merging**
